[weeks]

[weeks.intro]
key = "intro"
title = "Introduction"
date = "09-24"

[weeks.family]
key = "family"
title = "Language families, multilingualism, official languages"
date = "10-01"

[weeks.words]
key = "words"
title = "Vocabulary"
date = "10-08"

[weeks.features]
key = "features"
title = "Grammar"
date = "10-15"

# [weeks.holiday]
# key = "holiday"
# title = "Public Holiday"
# date = "10-28"
# other = "Independent Czechoslovak State Day"



[weeks.metaphor]
key = "metaphor"
title = "Metaphors across Languages"
date = "10-22"
other = ""

[weeks.minority]
key = "minority"
title = "Minority languages of Southeast and East Asia"
date = "10-29"

[weeks.reading]
key = "ðŸ“–"
title = "Reading week"
date = "11-05"


# [weeks.oral]
# key = "oral"
# title = "Oral literature and traditions"
# date = "11-04"


# [weeks.contact]
# key = "contact"
# title = "Language contact in SE and V Asia"
# date = "11-11"

[weeks.writing]
key = "writing"
title = "Writing, its origin, spread and adaptation"
date = "11-12"

[weeks.arts]
key = "arts"
title = "Communication and Culture"
date = "11-19"

[weeks.presentation1]
key = "Talk~1"
title = "Presentation on Minority Languages"
date = "11-26"
other = "Presentation! ðŸ—£"

[weeks.english]
key = "english"
title = "Asian Englishes"
date = "12-03"

[weeks.sounds]
key = "sounds"
title = "Sound Structure of Asian languages"
date = "12-10"
other =''

[weeks.presentation]
key = "Talk~2"
title = "Presentation of seminar work"
date = "12-16"
other = "Presentation!  ðŸ—£"


# [weeks.tones]
# key = "tones"
# title = "Tone in Asian Languages"
# date = "2024"
# other = "Guest Lecture (2024): Lian Hee Wee (Hong Kong Baptist)"
